In [267]:
# cardpole w/ use of env information - position, velocity and so on
import gym
import numpy as np
import importlib
import torch
import torch.nn as nn

# my modules
import network
import agent
importlib.reload(network)
importlib.reload(agent)

<module 'agent' from '/Users/mgaiduk/dev/repos/reinforcement_learning/03_py_cartpole/agent.py'>

In [269]:
t = 0
episodes = []
ag = agent.Agent(exploration_prob_decay_steps=100_000, lr=0.01)

env = gym.make('CartPole-v1').unwrapped
observation, info = env.reset(return_info=True)
for epoch in range(100_000):
    while True:
        # action = env.action_space.sample()
        action = ag.select_action(observation)
        observation, reward, done, info = env.step(action)
        ag.consume_event(observation, reward, done)
        if done:
            observation, info = env.reset(return_info=True)
            # print("Steps count: ", t)
            episodes.append(t)
            t = 0
            if epoch % 1000 == 0:
                print("Last 1000 games avg len: ", np.mean(episodes[-1000:]),
                      "max len: ", np.max(episodes[-1000:]))
            break
        t += 1
env.close()
print(np.mean(episodes), np.mean(episodes[-10:]), episodes[-10:])

0 12 tensor(43.8859, grad_fn=<MseLossBackward0>)	Last 1000 games avg len:  11.0 max len:  11
1000 20270 tensor(40.5814, grad_fn=<MseLossBackward0>)	Last 1000 games avg len:  19.258 max len:  76
2000 38864 tensor(77.3380, grad_fn=<MseLossBackward0>)	Last 1000 games avg len:  17.594 max len:  94
3000 68738 tensor(198.8994, grad_fn=<MseLossBackward0>)	Last 1000 games avg len:  28.874 max len:  126
4000 159688 tensor(578.4615, grad_fn=<MseLossBackward0>)	Last 1000 games avg len:  89.95 max len:  544
5000 268265 tensor(1657.8903, grad_fn=<MseLossBackward0>)	Last 1000 games avg len:  107.577 max len:  381
6000 415692 tensor(2174.7976, grad_fn=<MseLossBackward0>)	Last 1000 games avg len:  146.427 max len:  794
7000 440931 tensor(0.4187, grad_fn=<MseLossBackward0>)	Last 1000 games avg len:  24.239 max len:  314
8000 453506 tensor(4.5044, grad_fn=<MseLossBackward0>)	Last 1000 games avg len:  11.575 max len:  45
9000 572577 tensor(223.1597, grad_fn=<MseLossBackward0>)	Last 1000 games avg len:  1

Traceback (most recent call last):
  File "/Users/mgaiduk/miniforge3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3369, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/dr/kk0jd8fs4299j9b25qk4cdp00000gn/T/ipykernel_40307/371265494.py", line 10, in <cell line: 7>
    action = ag.select_action(observation)
  File "/Users/mgaiduk/dev/repos/reinforcement_learning/03_py_cartpole/agent.py", line 33, in select_action
    prediction = self.value_network(t)
  File "/Users/mgaiduk/miniforge3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/mgaiduk/dev/repos/reinforcement_learning/03_py_cartpole/network.py", line 21, in forward
    x = F.relu(layer(x))
  File "/Users/mgaiduk/miniforge3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/mgaiduk/miniforge3/lib/pyt

In [ ]:
i = 0
while True:
    # action = env.action_space.sample()
    t = torch.tensor(observation)
    # print(ag.value_network(t))
    action = ag.select_action(observation)
    observation, reward, done, info = env.step(action)
    ag.consume_event(observation, reward, done)
    if i % 1000 == 0:
        print(i)
    if done:
        observation, info = env.reset(return_info=True)
        # print("Steps count: ", t)
        break
    i += 1
t

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000


In [206]:
np.mean(episodes[-10:])

8.4

In [204]:
t = torch.tensor(observation)
t

tensor([-0.0385,  0.0102, -0.0481,  0.0293])

In [205]:
ag.value_network(t)

tensor([8.7231, 0.1875], grad_fn=<ReluBackward0>)

In [170]:
ag.observations, ag.rewards

([array([-0.04564317, -0.16140497,  0.04698385,  0.3242371 ], dtype=float32),
  array([-0.04887127, -0.35716334,  0.05346859,  0.6313588 ], dtype=float32),
  array([-0.05601454, -0.55298895,  0.06609577,  0.9403897 ], dtype=float32),
  array([-0.06707432, -0.74893653,  0.08490356,  1.2530873 ], dtype=float32),
  array([-0.08205305, -0.9450372 ,  0.10996531,  1.5711104 ], dtype=float32),
  array([-0.1009538 , -1.1412863 ,  0.14138752,  1.8959706 ], dtype=float32),
  array([-0.12377952, -1.3376296 ,  0.17930692,  2.2289762 ], dtype=float32)],
 [6.994, 5.995, 4.996, 3.997, 2.998, 1.999, 1.0])

In [174]:
predictions = ag.value_network(torch.tensor(ag.observations))
predictions

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], grad_fn=<ReluBackward0>)

In [173]:
values = torch.tensor(ag.rewards)
values

tensor([6.9940, 5.9950, 4.9960, 3.9970, 2.9980, 1.9990, 1.0000])

In [175]:
predicted_values = predictions.max(1)[0]
predicted_values

tensor([0., 0., 0., 0., 0., 0., 0.], grad_fn=<MaxBackward0>)

In [178]:
loss = nn.MSELoss(values, predicted_values)
loss

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [163]:
t = torch.tensor([observation, observation])
pred = ag.value_network(t)
pred

tensor([[0.0377, 0.1432],
        [0.0377, 0.1432]], grad_fn=<ReluBackward0>)

In [165]:
pred.max(1)[0]

tensor([0.1432, 0.1432], grad_fn=<MaxBackward0>)